Darknet: Network Struct Reference
Network Struct Reference
#include <network.hpp>
Public Member Functions
Network (string cfgfile, string weightfile)
virtual ~Network ()
void setBatch (size_t i)
void predict ()
Public Attributes
vector< Section * > sectionList
int n
int batch
size_t * seen
int * t
float epoch
int subdivisions
Layer * layers
float * output
float momentum
float decay
float gamma
float scale
float power
int time_steps
int step
int max_batches
float * scales
int * steps
int num_steps
int burn_in
int inputs
int outputs
int truths
int notruth
int h
int w
int c
int max_crop
int min_crop
float max_ratio
float min_ratio
int center
float angle
float aspect
float exposure
float saturation
float hue
int random
float * input
float * truth
float * delta
float * workspace
int train
int index
float * cost
float clip
Private Member Functions
void parseNetwork (string cfgfile)
void loadWeights (string weightfile)
Constructor & Destructor Documentation
Network()
Network::Network (string cfgfile, string weightfile)
 {
     try {
         parseNetwork(cfgfile);
         loadWeights(weightfile);
     }
     catch (const string error) {
         cout << error;
     }
 }
~Network()
Network::~Network () virtual
 {
     for (auto section: sectionList) {
         if (section) delete section;
     }
 }
Member Function Documentation
loadWeights()
void Network::loadWeights (string weightfile) private
 {
     FILE *fp = fopen("yolov3.weights", "wb");
     int major = 0;
     int minor = 2;
     int revision = 0;
     fwrite(&major, sizeof(int), 1, fp);
     fwrite(&minor, sizeof(int), 1, fp);
     fwrite(&revision, sizeof(int), 1, fp);
     if ((major*10 + minor) >= 2 && major < 1000 && minor < 1000) {
         fread(this->seen, sizeof(size_t), 1, fp);
     } else {
         int iseen = 0;
         fread(&iseen, sizeof(int), 1, fp);
         *(this->seen) = iseen;
     }
     int transpose = (major > 1000) || (minor > 1000);
     for (auto section: sectionList){
     }
     fclose(fp);
 }
parseNetwork()
void Network::parseNetwork (string cfgfile) private
 {
     fstream file(cfgfile.c_str(), ios::in);
     checkFile(file, cfgfile);
     vector<string> lines;
     fgetl(file, lines);
     for (string line: lines) {
         switch (line[0]) {
             case '[': {
                 int p = 1;
                 while (line[p] != ']') ++p;
                 LAYER_TYPE type = str2LayerType(line.substr(1, p-1));
                 Section* section = new Section(type);
                 sectionList.push_back(section);
             }
             case '\0':
             case '#':
             case ';':
                 break;
             default:
                 if (!readOption(line, (*(sectionList.end()-1))->params)) {
                     throw string("Could not parse: " + line + "\n");
                 }
                 break;
         }
     }
     file.close();
     // assign 第一層 network 的參數
     #define NET_SECTION sectionList[0]->params
     this->momentum = getf(NET_SECTION["momentum"], 0.9);
     this->decay = getf(NET_SECTION["decay"], 0.001);
     int subdivs = geti(NET_SECTION["subdivisions"], 1);
     this->time_steps = geti(NET_SECTION["time_steps"], 1);
     this->notruth = geti(NET_SECTION["notruth"], 0);
     this->batch /= subdivs;
     this->batch *= this->time_steps;
     this->subdivisions = subdivs;
     this->random = geti(NET_SECTION["random"], 0);
     this->h = geti(NET_SECTION["height"], 0);
     this->w = geti(NET_SECTION["width"], 0);
     this->c = geti(NET_SECTION["channels"], 0);
     this->inputs = geti(NET_SECTION["inputs"], this->h * this->w * this->c);
     this->max_crop = geti(NET_SECTION["max_crop"], this->w*2);
     this->min_crop = geti(NET_SECTION["min_crop"], this->w);
     this->max_ratio = getf(NET_SECTION["max_ratio"], (float) this->max_crop / this->w);
     this->min_ratio = getf(NET_SECTION["min_ratio"], (float) this->min_crop / this->w);
     this->center = geti(NET_SECTION["center"], 0);
     this->clip = geti(NET_SECTION["clip"], 0);
     #undef NET_SECTION
     sizeParams params;
     params.h = this->h;
     params.w = this->w;
     params.c = this->c;
     params.inputs = this->inputs;
     params.batch = this->batch;
     params.time_steps = this->time_steps;
     // 剩下每個 Section 已經讀到所有參數, 現在 assign 到 layer
     for (auto section: sectionList) {
         section->assignValue(params);
     }
 }
References checkFile(), fgetl(), getf(), geti(), NET_SECTION, readOption(), and str2LayerType().
predict()
void Network::predict ()
 {
 }
Referenced by detector().
setBatch()
void Network::setBatch (size_t i)
 {
     for (auto section: sectionList) {
         stringstream temp;
         temp << i;
         section->params["batch"] = temp.str();
     }
 }
Referenced by detector().
Member Data Documentation
angle
float Network::angle
aspect
float Network::aspect
batch
int Network::batch
burn_in
int Network::burn_in
c
int Network::c
center
int Network::center
clip
float Network::clip
cost
float* Network::cost
decay
float Network::decay
delta
float* Network::delta
epoch
float Network::epoch
exposure
float Network::exposure
gamma
float Network::gamma
h
int Network::h
hue
float Network::hue
index
int Network::index
input
float* Network::input
inputs
int Network::inputs
layers
Layer* Network::layers
max_batches
int Network::max_batches
max_crop
int Network::max_crop
max_ratio
float Network::max_ratio
min_crop
int Network::min_crop
min_ratio
float Network::min_ratio
momentum
float Network::momentum
n
int Network::n
notruth
int Network::notruth
num_steps
int Network::num_steps
output
float* Network::output
outputs
int Network::outputs
power
float Network::power
random
int Network::random
saturation
float Network::saturation
scale
float Network::scale
scales
float* Network::scales
sectionList
vector<Section*> Network::sectionList
seen
size_t* Network::seen
step
int Network::step
steps
int* Network::steps
subdivisions
int Network::subdivisions
t
int* Network::t
time_steps
int Network::time_steps
train
int Network::train
truth
float* Network::truth
truths
int Network::truths
w
int Network::w
workspace
float* Network::workspace
The documentation for this struct was generated from the following files:
src/network.hpp
src/network.cpp