Darknet: ConvLayer Struct Reference
ConvLayer Struct Reference
#include <conv_layer.hpp>
Public Member Functions
ConvLayer (std::map< string, string > &params, sizeParams size_params)
virtual ~ConvLayer ()
Additional Inherited Members
Public Attributes inherited from Layer
LAYER_TYPE type
ACTIVATION activation
COST_TYPE cost_type
void(* forward)(struct layer, struct network)
int batch_normalize
int shortcut
int batch
int forced
int flipped
int inputs
int outputs
int nweights
int nbiases
int extra
int truths
int h
int w
int c
int out_h
int out_w
int out_c
int n
int max_boxes
int groups
int size
int side
int stride
int reverse
int flatten
int spatial
int pad
int sqrt
int flip
int index
int binary
int xnor
int steps
int hidden
int truth
float smooth
float dot
float angle
float jitter
float saturation
float exposure
float shift
float ratio
float learning_rate_scale
float clip
int noloss
int softmax
int classes
int coords
int background
int rescore
int objectness
int joint
int noadjust
int reorg
int log
int tanh
int * mask
int total
float alpha
float beta
float kappa
float coord_scale
float object_scale
float noobject_scale
float mask_scale
float class_scale
int bias_match
int random
float ignore_thresh
float truth_thresh
float thresh
float focus
int classfix
int absolute
int onlyforward
int stopbackward
int dontload
int dontsave
int dontloadscales
int numload
float temperature
float probability
float scale
char * cweights
int * indexes
int * input_layers
int * input_sizes
int * map
int * counts
float ** sums
float * rand
float * cost
float * state
float * prev_state
float * forgot_state
float * forgot_delta
float * state_delta
float * combine_cpu
float * combine_delta_cpu
float * concat
float * concat_delta
float * binary_weights
float * biases
float * bias_updates
float * scales
float * scale_updates
float * weights
float * weight_updates
float * delta
float * output
float * loss
float * squared
float * norms
float * spatial_mean
float * mean
float * variance
float * mean_delta
float * variance_delta
float * rolling_mean
float * rolling_variance
float * x
float * x_norm
float * m
float * v
float * bias_m
float * bias_v
float * scale_m
float * scale_v
float * z_cpu
float * r_cpu
float * h_cpu
float * prev_state_cpu
float * temp_cpu
float * temp2_cpu
float * temp3_cpu
float * dh_cpu
float * hh_cpu
float * prev_cell_cpu
float * cell_cpu
float * f_cpu
float * i_cpu
float * g_cpu
float * o_cpu
float * c_cpu
float * dc_cpu
float * binary_input
struct layer * input_layer
struct layer * self_layer
struct layer * output_layer
struct layer * reset_layer
struct layer * update_layer
struct layer * state_layer
struct layer * input_gate_layer
struct layer * state_gate_layer
struct layer * input_save_layer
struct layer * state_save_layer
struct layer * input_state_layer
struct layer * state_state_layer
struct layer * input_z_layer
struct layer * state_z_layer
struct layer * input_r_layer
struct layer * state_r_layer
struct layer * input_h_layer
struct layer * state_h_layer
struct layer * wz
struct layer * uz
struct layer * wr
struct layer * ur
struct layer * wh
struct layer * uh
struct layer * uo
struct layer * wo
struct layer * uf
struct layer * wf
struct layer * ui
struct layer * wi
struct layer * ug
struct layer * wg
size_t workspace_size
Constructor & Destructor Documentation
ConvLayer()
ConvLayer::ConvLayer (std::map< string, string > & params, sizeParams size_params)
 {
     int n = geti(params["filters"], 1);
     int size = geti(params["size"], 1);
     int stride = geti(params["stride"], 1);
     int pad = geti(params["pad"], 0);
     int padding = geti(params["padding"], 0);
     int groups = geti(params["groups"], 1);
     if (pad > 0) padding = size/2;
     string activation_s = gets(params["activation"], "logistic");
     ACTIVATION activation = getActivation(activation_s);
     int batch, h, w, c;
     h = size_params.h;
     w = size_params.w;
     c = size_params.c;
     batch=size_params.batch;
     if (!(h && w && c)) throw string("Parse Conv Layer failed.");
     int batch_normalize = geti(params["batch_normalize"], 0);
     int binary = geti(params["binary"], 0);
     int xnor = geti(params["xnor"], 0);
     this->type = CONVOLUTIONAL;
     this->groups = groups;
     this->h = h;
     this->w = w;
     // l.c = c;
     this->c = c;
     // l.n = n;
     this->n = n;
     // l.binary = binary;
     this->binary = binary;
     // l.xnor = xnor;
     this->xnor = xnor;
     // l.batch = batch;
     this->batch = batch;
     // l.stride = stride;
     this->stride = stride;
     // l.size = size;
     this->size = size;
     // l.pad = padding;
     this->pad = padding;
     // l.batch_normalize = batch_normalize;
     this->batch_normalize = batch_normalize;
 }
References Layer::activation, Layer::batch, Layer::batch_normalize, Layer::binary, Layer::c, getActivation(), geti(), gets(), Layer::groups, Layer::h, Layer::n, Layer::pad, Layer::size, Layer::stride, Layer::type, Layer::w, and Layer::xnor.
~ConvLayer()
ConvLayer::~ConvLayer () virtual
 {
 }
The documentation for this struct was generated from the following files:
src/conv_layer.hpp
src/conv_layer.cpp